export const SAMPLE = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Exported at 07-07-2026 15:00:00 -->
<DEFTABLE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Folder.xsd">
<FOLDER DATACENTER="scmsap11" VERSION="921" PLATFORM="UNIX" FOLDER_NAME="01.정기작업" FOLDER_ORDER_METHOD="SYSTEM" TYPE="1">
  <JOB JOBISN="1" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin001001.sh" JOBNAME="BFIN001001_S01" DESCRIPTION="일배치 환경 초기화 및 락 파일 생성" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin001001.sh %%$ODATE 000 %%RUNCOUNT" DAYSCAL="DAILY" TIMEFROM="0005" MAXWAIT="7">
    <OUTCOND NAME="BFIN001001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="2" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin002001.sh" JOBNAME="BFIN002001_S01" DESCRIPTION="계좌 마스터 데이터 수신 (FTP)" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin002001.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0100" MAXWAIT="7">
    <INCOND NAME="BFIN001001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN002001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="3" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin002002.sh" JOBNAME="BFIN002002_S01" DESCRIPTION="카드 승인 내역 수신 (MQ)" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="cinfap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin002002.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0100" MAXWAIT="7">
    <INCOND NAME="BFIN001001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN002002_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="4" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin002003.sh" JOBNAME="BFIN002003_S01" DESCRIPTION="환율 정보 수신 (외부 API)" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin002003.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0100" MAXWAIT="5">
    <INCOND NAME="BFIN001001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN002003_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="5" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin003001.sh" JOBNAME="BFIN003001_S01" DESCRIPTION="수신 데이터 무결성 검증" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin003001.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0200" MAXWAIT="7">
    <INCOND NAME="BFIN002001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <INCOND NAME="BFIN002002_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <INCOND NAME="BFIN002003_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN003001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="6" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin004001.sh" JOBNAME="BFIN004001_S01" DESCRIPTION="계좌 데이터 표준화 변환" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin004001.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0300" MAXWAIT="7">
    <INCOND NAME="BFIN003001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN004001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="7" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin004002.sh" JOBNAME="BFIN004002_S01" DESCRIPTION="카드 승인 데이터 변환 및 집계" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="cinfap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin004002.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0300" MAXWAIT="7">
    <INCOND NAME="BFIN003001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN004002_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="8" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin005001.sh" JOBNAME="BFIN005001_S01" DESCRIPTION="데이터 웨어하우스 적재" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin005001.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0400" MAXWAIT="7">
    <INCOND NAME="BFIN004001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <INCOND NAME="BFIN004002_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN005001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="9" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin005002.sh" JOBNAME="BFIN005002_S01" DESCRIPTION="데이터 마트 적재 (요약 테이블)" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="cinfap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin005002.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0400" MAXWAIT="7">
    <INCOND NAME="BFIN004001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <INCOND NAME="BFIN004002_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN005002_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
  <JOB JOBISN="10" APPLICATION="FIN01.금융배치" SUB_APPLICATION="01.정기작업" MEMNAME="bfin010001.sh" JOBNAME="BFIN010001_S01" DESCRIPTION="일 마감 처리 및 다음 영업일 준비" RUN_AS="btapp" PRIORITY="AA" CRITICAL="1" TASKTYPE="Command" CYCLIC="0" NODEID="ccorap01" MEMLIB="/shrdat/batch/fin/shl/" CMDLINE="/shrdat/batch/fin/shl/bfin010001.sh %%$ODATE" DAYSCAL="DAILY" TIMEFROM="0800" MAXWAIT="7">
    <INCOND NAME="BFIN005001_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <INCOND NAME="BFIN005002_S01-OK" ODATE="ODAT" AND_OR="A"/>
    <OUTCOND NAME="BFIN010001_S01-OK" ODATE="ODAT" SIGN="+"/>
  </JOB>
</FOLDER>
</DEFTABLE>`;
